app.js
package-lock.json
package.json
views/partials/foot.ejs
views/partials/head.ejs

Done together app.js and views created

app.js created

---

app.js
package-lock.json
package.json
public/styles.css
views/index.ejs
views/partials/head.ejs

Title Page rough draft

---

config/config.json
migrations/20200529133720-create-user.js
migrations/20200529134119-create-room.js
migrations/20200529134923-create-message.js
migrations/20200529143730-mes_to_rm.js
migrations/20200529143731-users_to_mess.js
migrations/20200529154540-users_to_rooms.js
models/index.js
models/message.js
models/room.js
models/user.js
package-lock.json
package.json

database created

---

app.js
public/styles.css
views/mainchat.ejs

Main chat wireframe rough draft complete. Please review! Thanks in advance

Main Chat wireframe

---

package.json
seeders/20200529182834-dummyUsers.js
seeders/20200529184309-dummyRooms.js
seeders/20200529185115-dummyMessages.js
seeders/20200529185600-dummyUserRooms.js

Added seeders

---

app.js

adds routes for different rooms

---

views/atlantachat.ejs
views/codingchat.ejs
views/petchat.ejs

This should do it - awesome job team.

Rooms renamed

---

app.js
package-lock.json
package.json
views/atlantachat.ejs
views/codingchat.ejs
views/mainchat.ejs
views/petchat.ejs

Fixes log out button. Please review

functional logout button

---

public/styles.css
views/atlantachat.ejs
views/codingchat.ejs
views/mainchat.ejs
views/petchat.ejs

Updated styles, please review. Thanks in advance!

Style updated

---

views/codingchat.ejs
views/petchat.ejs

small formatting errors fixed! Thanks in advance!

Fixed small errors

---

app.js
public/index.js
views/atlantachat.ejs
views/codingchat.ejs
views/index.ejs
views/mainchat.ejs
views/private.ejs

Code is working, beginning to implement Private Chat functionality.

Working on private chat

---

app.js
models/message.js
public/index.js
views/petchat.ejs

Here is the most recent update - thanks team!

latest and greatest

---

app.js
views/mainchat.ejs

Modal has been fixed, let me know what you think! thank you

Modal updated

---

app.js
public/index.js
views/mainchat.ejs

name issue should be fixed, nice catch Zahria!

fixed chat issue

---

app.js
public/index.js

chat room tracker is now working. All should be well

Chat room locator working

---

public/index.js
views/atlantachat.ejs
views/codingchat.ejs
views/petchat.ejs

room names have been reformatted. Please check and merge. Thanks!

reformatted room names

---

public/index.js
views/atlantachat.ejs
views/codingchat.ejs
views/index.ejs
views/petchat.ejs

private chat modal is now working in all rooms, thank you thank you

private chat in all rooms

---

public/styles.css

made the online users column slightly wider

widened column

---

seeders/20200529182834-dummyUsers.js
seeders/20200529184309-dummyRooms.js
seeders/20200529185115-dummyMessages.js

Adding updated seeder code for the DB.

updated seeder content

---

models/message.js
public/index.js
public/styles.css
views/atlantachat.ejs
views/codingchat.ejs
views/petchat.ejs

stlye change

---

app.js
models/message.js
public/index.js
public/styles.css
views/atlantachat.ejs
views/codingchat.ejs
views/mainchat.ejs
views/petchat.ejs

Updated styles and EJS templates

style updates

---

models/message.js

changes time from military time. please review

time changes
